import { Lato } from 'next/font/google';
import './globals.css';

const lato = Lato({
	subsets: ['latin'],
	weight: ['100', '300', '400', '700', '900'],
	variable: '--font-lato', // CSS variable for Tailwind
	display: 'swap',
});

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang="en" className={lato.className}>
			<body className={`antialiased font-lato`}>
				{children}
			</body>
		</html>
	);
}
